# Generated by Django 6.0.6 on 2026-06-19 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_user_phone_number_voterregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_voter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voterregister',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('vote_cast', 'Vote Cast'), ('voter_registered', 'Voter Registered'), ('voter_deactivated', 'Voter Deactivated'), ('voter_activated', 'Voter Activated'), ('election_created', 'Election Created'), ('election_activated', 'Election Activated'), ('election_closed', 'Election Closed'), ('bulk_upload', 'Bulk Upload')], max_length=50)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='elections.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
