# Generated by Django 6.0.6 on 2026-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_user_is_active_voter_voterregister_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_url_direct',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
